
import Link from 'next/link';
import { Leaf, ShieldCheck, Microscope } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Logo } from '@/components/icons';
import { WaveBackground } from '@/components/WaveBackground';

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
  return (
    <div className="flex flex-col items-center text-center p-6 bg-card/80 backdrop-blur-sm rounded-lg shadow-md z-10">
      <div className="p-3 bg-primary/10 rounded-full mb-4">
        {icon}
      </div>
      <h3 className="text-lg font-bold mb-2 text-primary">{title}</h3>
      <p className="text-muted-foreground">{description}</p>
    </div>
  );
}

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-background relative overflow-hidden">
      <WaveBackground />
      <header className="py-4 px-4 md:px-8 flex items-center gap-4 z-10 relative">
        <Logo />
        <div>
          <h1 className="text-2xl font-bold font-headline text-primary">CropSafe AI</h1>
          <p className="text-muted-foreground">Your AI-powered agricultural assistant</p>
        </div>
      </header>

      <main className="flex-grow container mx-auto px-4 py-8 text-center">
        <div className="max-w-4xl mx-auto z-10 relative">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Instant Plant Disease Detection
          </h2>
          <p className="text-xl text-muted-foreground mb-8">
            Protect your crops with the power of AI. Just upload a photo of a leaf, and get an instant diagnosis and treatment plan.
          </p>
          <Link href="/analyze">
            <Button size="lg">
              <Leaf className="mr-2" /> Start Analysis
            </Button>
          </Link>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mt-16 text-left">
          <FeatureCard
            icon={<Microscope className="h-8 w-8 text-accent" />}
            title="Advanced AI Analysis"
            description="Our powerful AI model analyzes leaf images to detect a wide range of diseases with high accuracy, giving you a confidence score for each diagnosis."
          />
          <FeatureCard
            icon={<ShieldCheck className="h-8 w-8 text-accent" />}
            title="Expert Treatment Guidance"
            description="Receive clear, actionable treatment advice generated by AI. Our guidance helps you manage diseases and protect your crop yield effectively."
          />
          <FeatureCard
            icon={<Leaf className="h-8 w-8 text-accent" />}
            title="Easy to Use"
            description="Simply upload a photo of a plant leaf. Our intuitive interface makes it easy for anyone to get a fast and reliable plant health analysis."
          />
        </div>
      </main>

      <footer className="text-center p-4 text-sm text-muted-foreground z-10 relative">
        © {new Date().getFullYear()} CropSafe AI. All rights reserved.
      </footer>
    </div>
  );
}
